version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - redis
      - kafka

  kafka-manager:
    image: "scrapinghub/kafka-manager"
    environment:
      ZK_HOSTS: "zookeeper:2181"
    ports:
      - "9000:9000"
    links:
      - kafka

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - zookeeper
    restart: always

  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    restart: always
  
  redis:
    image: "redis:alpine"
    restart: always
