version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    entrypoint: "python run.py"
    links:
      - redis
      - kafka
    logging:
      driver : "none"

  consumer:
    build: .
    entrypoint: "python consumer.py"
    volumes:
      - .:/app
    links:
      - redis
      - kafka

  kafka-manager:
    image: "scrapinghub/kafka-manager"
    environment:
      ZK_HOSTS: "zookeeper:2181"
    ports:
      - "9000:9000"
    links:
      - kafka

  kafka:
    image: "wurstmeister/kafka"
    ports:
      - "9092:9092"
      - "9999:9999"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      JMX_PORT: 9999
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
        test: ["CMD", "ping", "-c", "1", "kafka:9092"]
        interval: 30s
        timeout: 10s
        retries: 5
    links:
      - zookeeper

  zookeeper:
    image: "wurstmeister/zookeeper"
    ports:
      - "2181:2181"
    healthcheck:
      test: "exit 0"
    restart: always
  
  redis:
    image: "redis:alpine"
    healthcheck:
      test: "exit 0"
